// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJWN9Js_DSVQvT-ojzGRCEWnUZtf5EKBc',
    appId: '1:19042067110:web:5ba2b5bde8c16b36878a67',
    messagingSenderId: '19042067110',
    projectId: 'social-app-6bea7',
    authDomain: 'social-app-6bea7.firebaseapp.com',
    storageBucket: 'social-app-6bea7.appspot.com',
    measurementId: 'G-BZCRJBBYD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUCgjA78zJH9hT_Aepg1a25BGNrkhTVw0',
    appId: '1:19042067110:android:1763651800cf6b6b878a67',
    messagingSenderId: '19042067110',
    projectId: 'social-app-6bea7',
    storageBucket: 'social-app-6bea7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA348Psctf-7sHFpq4AAivchky1zWlU3vA',
    appId: '1:19042067110:ios:005d82e33eb52ff5878a67',
    messagingSenderId: '19042067110',
    projectId: 'social-app-6bea7',
    storageBucket: 'social-app-6bea7.appspot.com',
    iosClientId: '19042067110-iqgmd3ji0bm6ofv240ti7glehepfh75l.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA348Psctf-7sHFpq4AAivchky1zWlU3vA',
    appId: '1:19042067110:ios:e0121a391ccc1dae878a67',
    messagingSenderId: '19042067110',
    projectId: 'social-app-6bea7',
    storageBucket: 'social-app-6bea7.appspot.com',
    iosClientId: '19042067110-dnmjkg73oc81f9qit854l9bqjrcd4f5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.social.RunnerTests',
  );
}
